WANDB_API_KEY='0df2bb005b0367568689f62cc7dcd9e521f4e70b'
WANDB_TIMEOUT = '60'
WANDB_ENTITY = '1643921154-peking-university'
WEAVE_OPEN = False
TASKS_CFG_PATH = 'configs/eval_configs/'
TASKS = {

# ======================================werewolf========================================
"eval_deepseek-v25_werewolf_scene1_deepseek-v25_vs_gpt-4o-mini": "eval_deepseek-v25_werewolf_scene1_deepseek-v25_vs_gpt-4o-mini.yaml",
"eval_gemini-15-flash_werewolf_scene1_gemini-15-flash_vs_gpt-4o-mini": "eval_gemini-15-flash_werewolf_scene1_gemini-15-flash_vs_gpt-4o-mini.yaml",
"eval_gpt-35-turbo-0125_werewolf_scene1_gpt-35-turbo-0125_vs_gpt-4o-mini": "eval_gpt-35-turbo-0125_werewolf_scene1_gpt-35-turbo-0125_vs_gpt-4o-mini.yaml",
"eval_GPT-4o_werewolf_scene1_GPT-4o_vs_gpt-4o-mini": "eval_GPT-4o_werewolf_scene1_GPT-4o_vs_gpt-4o-mini.yaml",
"eval_o1-mini_werewolf_scene1_o1-mini_vs_gpt-4o-mini": "eval_o1-mini_werewolf_scene1_o1-mini_vs_gpt-4o-mini.yaml",
# "eval_llama31-70b_werewolf_scene1_llama31-70b_vs_gpt-4o-mini": "eval_llama31-70b_werewolf_scene1_llama31-70b_vs_gpt-4o-mini.yaml",
# "eval_llama31-8b_werewolf_scene1_llama31-8b_vs_gpt-4o-mini": "eval_llama31-8b_werewolf_scene1_llama31-8b_vs_gpt-4o-mini.yaml",
# "eval_qwen-25_werewolf_scene1_qwen-25_vs_gpt-4o-mini": "eval_qwen-25_werewolf_scene1_qwen-25_vs_gpt-4o-mini.yaml",
# "eval_claude-3-haiku_werewolf_scene1_claude-3-haiku_vs_gpt-4o-mini": "eval_claude-3-haiku_werewolf_scene1_claude-3-haiku_vs_gpt-4o-mini.yaml",
#

}


#======================================welfare-diplomacy========================================
#
#
##"eval_deepseek-v25_welfare_diplomacy_scene1_deepseek-v25_vs_gpt-4o-mini": "eval_deepseek-v25_welfare_diplomacy_scene1_deepseek-v25_vs_gpt-4o-mini.yaml",
##"eval_gemini-15-flash_welfare_diplomacy_scene1_gemini-15-flash_vs_gpt-4o-mini": "eval_gemini-15-flash_welfare_diplomacy_scene1_gemini-15-flash_vs_gpt-4o-mini.yaml",
##"eval_gpt-35-turbo-0125_welfare_diplomacy_scene1_gpt-35-turbo-0125_vs_gpt-4o-mini": "eval_gpt-35-turbo-0125_welfare_diplomacy_scene1_gpt-35-turbo-0125_vs_gpt-4o-mini.yaml",
##"eval_GPT-4o_welfare_diplomacy_scene1_GPT-4o_vs_gpt-4o-mini": "eval_GPT-4o_welfare_diplomacy_scene1_GPT-4o_vs_gpt-4o-mini.yaml",
##"eval_o1-mini_welfare_diplomacy_scene1_o1-mini_vs_gpt-4o-mini": "eval_o1-mini_welfare_diplomacy_scene1_o1-mini_vs_gpt-4o-mini.yaml",
# "eval_llama31-70b_welfare_diplomacy_scene1_llama31-70b_vs_gpt-4o-mini": "eval_llama31-70b_welfare_diplomacy_scene1_llama31-70b_vs_gpt-4o-mini.yaml",
# "eval_llama31-8b_welfare_diplomacy_scene1_llama31-8b_vs_gpt-4o-mini": "eval_llama31-8b_welfare_diplomacy_scene1_llama31-8b_vs_gpt-4o-mini.yaml",

# #======================================civ========================================
##"eval_deepseek-v25_civ_scene1_agent_run_myagent_T1_WORLDSMALL": "eval_deepseek-v25_civ_scene1_agent_run_myagent_T1_WORLDSMALL.yaml",
##"eval_deepseek-v25_civ_scene2_agent_run_myagent_T1_BRITISHAISLES": "eval_deepseek-v25_civ_scene2_agent_run_myagent_T1_BRITISHAISLES.yaml",
##"eval_deepseek-v25_civ_scene3_agent_run_myagent_T1_FRANCE": "eval_deepseek-v25_civ_scene3_agent_run_myagent_T1_FRANCE.yaml",
##"eval_gemini-15-flash_civ_scene1_agent_run_myagent_T1_WORLDSMALL": "eval_gemini-15-flash_civ_scene1_agent_run_myagent_T1_WORLDSMALL.yaml",
##"eval_gemini-15-flash_civ_scene2_agent_run_myagent_T1_BRITISHAISLES": "eval_gemini-15-flash_civ_scene2_agent_run_myagent_T1_BRITISHAISLES.yaml",
##"eval_gemini-15-flash_civ_scene3_agent_run_myagent_T1_FRANCE": "eval_gemini-15-flash_civ_scene3_agent_run_myagent_T1_FRANCE.yaml",
##"eval_gpt-35-turbo-0125_civ_scene1_agent_run_myagent_T1_WORLDSMALL": "eval_gpt-35-turbo-0125_civ_scene1_agent_run_myagent_T1_WORLDSMALL.yaml",
##"eval_gpt-35-turbo-0125_civ_scene2_agent_run_myagent_T1_BRITISHAISLES": "eval_gpt-35-turbo-0125_civ_scene2_agent_run_myagent_T1_BRITISHAISLES.yaml",
##"eval_gpt-35-turbo-0125_civ_scene3_agent_run_myagent_T1_FRANCE": "eval_gpt-35-turbo-0125_civ_scene3_agent_run_myagent_T1_FRANCE.yaml",
##"eval_gpt-4o-mini_civ_scene1_agent_run_myagent_T1_WORLDSMALL": "eval_gpt-4o-mini_civ_scene1_agent_run_myagent_T1_WORLDSMALL.yaml",
##"eval_gpt-4o-mini_civ_scene2_agent_run_myagent_T1_BRITISHAISLES": "eval_gpt-4o-mini_civ_scene2_agent_run_myagent_T1_BRITISHAISLES.yaml",
##"eval_gpt-4o-mini_civ_scene3_agent_run_myagent_T1_FRANCE": "eval_gpt-4o-mini_civ_scene3_agent_run_myagent_T1_FRANCE.yaml",
##"eval_GPT-4o_civ_scene1_agent_run_myagent_T1_WORLDSMALL": "eval_GPT-4o_civ_scene1_agent_run_myagent_T1_WORLDSMALL.yaml",
##"eval_GPT-4o_civ_scene2_agent_run_myagent_T1_BRITISHAISLES": "eval_GPT-4o_civ_scene2_agent_run_myagent_T1_BRITISHAISLES.yaml",
##"eval_GPT-4o_civ_scene3_agent_run_myagent_T1_FRANCE": "eval_GPT-4o_civ_scene3_agent_run_myagent_T1_FRANCE.yaml",
##"eval_o1-mini_civ_scene1_agent_run_myagent_T1_WORLDSMALL": "eval_o1-mini_civ_scene1_agent_run_myagent_T1_WORLDSMALL.yaml",
##"eval_o1-mini_civ_scene2_agent_run_myagent_T1_BRITISHAISLES": "eval_o1-mini_civ_scene2_agent_run_myagent_T1_BRITISHAISLES.yaml",
##"eval_o1-mini_civ_scene3_agent_run_myagent_T1_FRANCE": "eval_o1-mini_civ_scene3_agent_run_myagent_T1_FRANCE.yaml",
# "eval_llama31-70b_civ_scene1_agent_run_myagent_T1_WORLDSMALL": "eval_llama31-70b_civ_scene1_agent_run_myagent_T1_WORLDSMALL.yaml",
# "eval_llama31-70b_civ_scene2_agent_run_myagent_T1_BRITISHAISLES": "eval_llama31-70b_civ_scene2_agent_run_myagent_T1_BRITISHAISLES.yaml",
# "eval_llama31-70b_civ_scene3_agent_run_myagent_T1_FRANCE": "eval_llama31-70b_civ_scene3_agent_run_myagent_T1_FRANCE.yaml",
# "eval_llama31-8b_civ_scene1_agent_run_myagent_T1_WORLDSMALL": "eval_llama31-8b_civ_scene1_agent_run_myagent_T1_WORLDSMALL.yaml",
# "eval_llama31-8b_civ_scene2_agent_run_myagent_T1_BRITISHAISLES": "eval_llama31-8b_civ_scene2_agent_run_myagent_T1_BRITISHAISLES.yaml",
# "eval_llama31-8b_civ_scene3_agent_run_myagent_T1_FRANCE": "eval_llama31-8b_civ_scene3_agent_run_myagent_T1_FRANCE.yaml",

# #======================================streetfight3========================================
##"eval_deepseek-v25_streetfight3_scene1_deepseek-v25_vs_gpt-4o-mini_asyTrue": "eval_deepseek-v25_streetfight3_scene1_deepseek-v25_vs_gpt-4o-mini_asyTrue.yaml",
##"eval_deepseek-v25_streetfight3_scene2_deepseek-v25_vs_gpt-4o-mini_asyFalse": "eval_deepseek-v25_streetfight3_scene2_deepseek-v25_vs_gpt-4o-mini_asyFalse.yaml",
##"eval_gemini-15-flash_streetfight3_scene1_gemini-15-flash_vs_gpt-4o-mini_asyTrue": "eval_gemini-15-flash_streetfight3_scene1_gemini-15-flash_vs_gpt-4o-mini_asyTrue.yaml",
##"eval_gemini-15-flash_streetfight3_scene2_gemini-15-flash_vs_gpt-4o-mini_asyFalse": "eval_gemini-15-flash_streetfight3_scene2_gemini-15-flash_vs_gpt-4o-mini_asyFalse.yaml",
##"eval_gpt-35-turbo-0125_streetfight3_scene1_gpt-35-turbo-0125_vs_gpt-4o-mini_asyTrue": "eval_gpt-35-turbo-0125_streetfight3_scene1_gpt-35-turbo-0125_vs_gpt-4o-mini_asyTrue.yaml",
##"eval_gpt-35-turbo-0125_streetfight3_scene2_gpt-35-turbo-0125_vs_gpt-4o-mini_asyFalse": "eval_gpt-35-turbo-0125_streetfight3_scene2_gpt-35-turbo-0125_vs_gpt-4o-mini_asyFalse.yaml",
##"eval_GPT-4o_streetfight3_scene1_GPT-4o_vs_gpt-4o-mini_asyTrue": "eval_GPT-4o_streetfight3_scene1_GPT-4o_vs_gpt-4o-mini_asyTrue.yaml",
##"eval_GPT-4o_streetfight3_scene2_GPT-4o_vs_gpt-4o-mini_asyFalse": "eval_GPT-4o_streetfight3_scene2_GPT-4o_vs_gpt-4o-mini_asyFalse.yaml",
##"eval_o1-mini_streetfight3_scene1_o1-mini_vs_gpt-4o-mini_asyTrue": "eval_o1-mini_streetfight3_scene1_o1-mini_vs_gpt-4o-mini_asyTrue.yaml",
##"eval_o1-mini_streetfight3_scene2_o1-mini_vs_gpt-4o-mini_asyFalse": "eval_o1-mini_streetfight3_scene2_o1-mini_vs_gpt-4o-mini_asyFalse.yaml",
# "eval_llama31-70b_streetfight3_scene1_llama31-70b_vs_gpt-4o-mini_asyTrue": "eval_llama31-70b_streetfight3_scene1_llama31-70b_vs_gpt-4o-mini_asyTrue.yaml",
# "eval_llama31-70b_streetfight3_scene2_llama31-70b_vs_gpt-4o-mini_asyFalse": "eval_llama31-70b_streetfight3_scene2_llama31-70b_vs_gpt-4o-mini_asyFalse.yaml",
# "eval_llama31-8b_streetfight3_scene1_llama31-8b_vs_gpt-4o-mini_asyTrue": "eval_llama31-8b_streetfight3_scene1_llama31-8b_vs_gpt-4o-mini_asyTrue.yaml",
# "eval_llama31-8b_streetfight3_scene2_llama31-8b_vs_gpt-4o-mini_asyFalse": "eval_llama31-8b_streetfight3_scene2_llama31-8b_vs_gpt-4o-mini_asyFalse.yaml",
# #
#======================================stratego========================================
##"eval_deepseek-v25_stratego_scene1_deepseek-v25_vs_gpt-4o-mini_random": "eval_deepseek-v25_stratego_scene1_deepseek-v25_vs_gpt-4o-mini_random.yaml",
##"eval_deepseek-v25_stratego_scene2_deepseek-v25_vs_gpt-4o-mini_fixed": "eval_deepseek-v25_stratego_scene2_deepseek-v25_vs_gpt-4o-mini_fixed.yaml",
##"eval_gemini-15-flash_stratego_scene1_gemini-15-flash_vs_gpt-4o-mini_random": "eval_gemini-15-flash_stratego_scene1_gemini-15-flash_vs_gpt-4o-mini_random.yaml",
##"eval_gemini-15-flash_stratego_scene2_gemini-15-flash_vs_gpt-4o-mini_fixed": "eval_gemini-15-flash_stratego_scene2_gemini-15-flash_vs_gpt-4o-mini_fixed.yaml",
##"eval_gpt-35-turbo-0125_stratego_scene1_gpt-35-turbo-0125_vs_gpt-4o-mini_random": "eval_gpt-35-turbo-0125_stratego_scene1_gpt-35-turbo-0125_vs_gpt-4o-mini_random.yaml",
##"eval_gpt-35-turbo-0125_stratego_scene2_gpt-35-turbo-0125_vs_gpt-4o-mini_fixed": "eval_gpt-35-turbo-0125_stratego_scene2_gpt-35-turbo-0125_vs_gpt-4o-mini_fixed.yaml",
##"eval_GPT-4o_stratego_scene1_GPT-4o_vs_gpt-4o-mini_random": "eval_GPT-4o_stratego_scene1_GPT-4o_vs_gpt-4o-mini_random.yaml",
##"eval_GPT-4o_stratego_scene2_GPT-4o_vs_gpt-4o-mini_fixed": "eval_GPT-4o_stratego_scene2_GPT-4o_vs_gpt-4o-mini_fixed.yaml",
##"eval_o1-mini_stratego_scene1_o1-mini_vs_gpt-4o-mini_random": "eval_o1-mini_stratego_scene1_o1-mini_vs_gpt-4o-mini_random.yaml",
##"eval_o1-mini_stratego_scene2_o1-mini_vs_gpt-4o-mini_fixed": "eval_o1-mini_stratego_scene2_o1-mini_vs_gpt-4o-mini_fixed.yaml",
# "eval_llama31-70b_stratego_scene1_llama31-70b_vs_gpt-4o-mini_random": "eval_llama31-70b_stratego_scene1_llama31-70b_vs_gpt-4o-mini_random.yaml",
# "eval_llama31-70b_stratego_scene2_llama31-70b_vs_gpt-4o-mini_fixed": "eval_llama31-70b_stratego_scene2_llama31-70b_vs_gpt-4o-mini_fixed.yaml",
# "eval_llama31-8b_stratego_scene1_llama31-8b_vs_gpt-4o-mini_random": "eval_llama31-8b_stratego_scene1_llama31-8b_vs_gpt-4o-mini_random.yaml",
# "eval_llama31-8b_stratego_scene2_llama31-8b_vs_gpt-4o-mini_fixed": "eval_llama31-8b_stratego_scene2_llama31-8b_vs_gpt-4o-mini_fixed.yaml",
# "eval_claude-3-haiku_stratego_scene2_claude-3-haiku_vs_gpt-4o-mini_fixed": "eval_claude-3-haiku_stratego_scene2_claude-3-haiku_vs_gpt-4o-mini_fixed.yaml",
# "eval_claude-3-haiku_stratego_scene1_claude-3-haiku_vs_gpt-4o-mini_random": "eval_claude-3-haiku_stratego_scene1_claude-3-haiku_vs_gpt-4o-mini_random.yaml",
#
#
# #======================================starcraft2========================================
##"eval_deepseek-v25_starcraft2_scene1_agent_vs_computer_macro_asyFalse": "eval_deepseek-v25_starcraft2_scene1_agent_vs_computer_macro_asyFalse.yaml",
##"eval_deepseek-v25_starcraft2_scene2_agent_vs_computer_macro_asyTrue": "eval_deepseek-v25_starcraft2_scene2_agent_vs_computer_macro_asyTrue.yaml",
##"eval_deepseek-v25_starcraft2_scene3_agent_vs_computer_rush_asyFalse": "eval_deepseek-v25_starcraft2_scene3_agent_vs_computer_rush_asyFalse.yaml",
##"eval_deepseek-v25_starcraft2_scene4_agent_vs_computer_rush_asyTrue": "eval_deepseek-v25_starcraft2_scene4_agent_vs_computer_rush_asyTrue.yaml",
##"eval_deepseek-v25_starcraft2_scene5_agent_vs_computer_randombuild_asyFalse": "eval_deepseek-v25_starcraft2_scene5_agent_vs_computer_randombuild_asyFalse.yaml",
##"eval_deepseek-v25_starcraft2_scene6_agent_vs_computer_randombuild_asyTrue": "eval_deepseek-v25_starcraft2_scene6_agent_vs_computer_randombuild_asyTrue.yaml",
##"eval_gemini-15-flash_starcraft2_scene1_agent_vs_computer_macro_asyFalse": "eval_gemini-15-flash_starcraft2_scene1_agent_vs_computer_macro_asyFalse.yaml",
##"eval_gemini-15-flash_starcraft2_scene2_agent_vs_computer_macro_asyTrue": "eval_gemini-15-flash_starcraft2_scene2_agent_vs_computer_macro_asyTrue.yaml",
##"eval_gemini-15-flash_starcraft2_scene3_agent_vs_computer_rush_asyFalse": "eval_gemini-15-flash_starcraft2_scene3_agent_vs_computer_rush_asyFalse.yaml",
##"eval_gemini-15-flash_starcraft2_scene4_agent_vs_computer_rush_asyTrue": "eval_gemini-15-flash_starcraft2_scene4_agent_vs_computer_rush_asyTrue.yaml",
##"eval_gemini-15-flash_starcraft2_scene5_agent_vs_computer_randombuild_asyFalse": "eval_gemini-15-flash_starcraft2_scene5_agent_vs_computer_randombuild_asyFalse.yaml",
##"eval_gemini-15-flash_starcraft2_scene6_agent_vs_computer_randombuild_asyTrue": "eval_gemini-15-flash_starcraft2_scene6_agent_vs_computer_randombuild_asyTrue.yaml",
##"eval_gpt-35-turbo-0125_starcraft2_scene1_agent_vs_computer_macro_asyFalse": "eval_gpt-35-turbo-0125_starcraft2_scene1_agent_vs_computer_macro_asyFalse.yaml",
##"eval_gpt-35-turbo-0125_starcraft2_scene2_agent_vs_computer_macro_asyTrue": "eval_gpt-35-turbo-0125_starcraft2_scene2_agent_vs_computer_macro_asyTrue.yaml",
##"eval_gpt-35-turbo-0125_starcraft2_scene3_agent_vs_computer_rush_asyFalse": "eval_gpt-35-turbo-0125_starcraft2_scene3_agent_vs_computer_rush_asyFalse.yaml",
##"eval_gpt-35-turbo-0125_starcraft2_scene4_agent_vs_computer_rush_asyTrue": "eval_gpt-35-turbo-0125_starcraft2_scene4_agent_vs_computer_rush_asyTrue.yaml",
##"eval_gpt-35-turbo-0125_starcraft2_scene5_agent_vs_computer_randombuild_asyFalse": "eval_gpt-35-turbo-0125_starcraft2_scene5_agent_vs_computer_randombuild_asyFalse.yaml",
##"eval_gpt-35-turbo-0125_starcraft2_scene6_agent_vs_computer_randombuild_asyTrue": "eval_gpt-35-turbo-0125_starcraft2_scene6_agent_vs_computer_randombuild_asyTrue.yaml",
##"eval_gpt-4o-mini_starcraft2_scene1_agent_vs_computer_macro_asyFalse": "eval_gpt-4o-mini_starcraft2_scene1_agent_vs_computer_macro_asyFalse.yaml",
##"eval_gpt-4o-mini_starcraft2_scene2_agent_vs_computer_macro_asyTrue": "eval_gpt-4o-mini_starcraft2_scene2_agent_vs_computer_macro_asyTrue.yaml",
##"eval_gpt-4o-mini_starcraft2_scene3_agent_vs_computer_rush_asyFalse": "eval_gpt-4o-mini_starcraft2_scene3_agent_vs_computer_rush_asyFalse.yaml",
##"eval_gpt-4o-mini_starcraft2_scene4_agent_vs_computer_rush_asyTrue": "eval_gpt-4o-mini_starcraft2_scene4_agent_vs_computer_rush_asyTrue.yaml",
##"eval_gpt-4o-mini_starcraft2_scene5_agent_vs_computer_randombuild_asyFalse": "eval_gpt-4o-mini_starcraft2_scene5_agent_vs_computer_randombuild_asyFalse.yaml",
##"eval_gpt-4o-mini_starcraft2_scene6_agent_vs_computer_randombuild_asyTrue": "eval_gpt-4o-mini_starcraft2_scene6_agent_vs_computer_randombuild_asyTrue.yaml",
##"eval_GPT-4o_starcraft2_scene1_agent_vs_computer_macro_asyFalse": "eval_GPT-4o_starcraft2_scene1_agent_vs_computer_macro_asyFalse.yaml",
##"eval_GPT-4o_starcraft2_scene2_agent_vs_computer_macro_asyTrue": "eval_GPT-4o_starcraft2_scene2_agent_vs_computer_macro_asyTrue.yaml",
##"eval_GPT-4o_starcraft2_scene3_agent_vs_computer_rush_asyFalse": "eval_GPT-4o_starcraft2_scene3_agent_vs_computer_rush_asyFalse.yaml",
##"eval_GPT-4o_starcraft2_scene4_agent_vs_computer_rush_asyTrue": "eval_GPT-4o_starcraft2_scene4_agent_vs_computer_rush_asyTrue.yaml",
##"eval_GPT-4o_starcraft2_scene5_agent_vs_computer_randombuild_asyFalse": "eval_GPT-4o_starcraft2_scene5_agent_vs_computer_randombuild_asyFalse.yaml",
##"eval_GPT-4o_starcraft2_scene6_agent_vs_computer_randombuild_asyTrue": "eval_GPT-4o_starcraft2_scene6_agent_vs_computer_randombuild_asyTrue.yaml",
##"eval_o1-mini_starcraft2_scene1_agent_vs_computer_macro_asyFalse": "eval_o1-mini_starcraft2_scene1_agent_vs_computer_macro_asyFalse.yaml",
##"eval_o1-mini_starcraft2_scene2_agent_vs_computer_macro_asyTrue": "eval_o1-mini_starcraft2_scene2_agent_vs_computer_macro_asyTrue.yaml",
##"eval_o1-mini_starcraft2_scene3_agent_vs_computer_rush_asyFalse": "eval_o1-mini_starcraft2_scene3_agent_vs_computer_rush_asyFalse.yaml",
##"eval_o1-mini_starcraft2_scene4_agent_vs_computer_rush_asyTrue": "eval_o1-mini_starcraft2_scene4_agent_vs_computer_rush_asyTrue.yaml",
##"eval_o1-mini_starcraft2_scene5_agent_vs_computer_randombuild_asyFalse": "eval_o1-mini_starcraft2_scene5_agent_vs_computer_randombuild_asyFalse.yaml",
##"eval_o1-mini_starcraft2_scene6_agent_vs_computer_randombuild_asyTrue": "eval_o1-mini_starcraft2_scene6_agent_vs_computer_randombuild_asyTrue.yaml"
# "eval_llama31-70b_starcraft2_scene1_agent_vs_computer_macro_asyFalse": "eval_llama31-70b_starcraft2_scene1_agent_vs_computer_macro_asyFalse.yaml",
# "eval_llama31-70b_starcraft2_scene2_agent_vs_computer_macro_asyTrue": "eval_llama31-70b_starcraft2_scene2_agent_vs_computer_macro_asyTrue.yaml",
# "eval_llama31-70b_starcraft2_scene3_agent_vs_computer_rush_asyFalse": "eval_llama31-70b_starcraft2_scene3_agent_vs_computer_rush_asyFalse.yaml",
# "eval_llama31-70b_starcraft2_scene4_agent_vs_computer_rush_asyTrue": "eval_llama31-70b_starcraft2_scene4_agent_vs_computer_rush_asyTrue.yaml",
# "eval_llama31-70b_starcraft2_scene5_agent_vs_computer_randombuild_asyFalse": "eval_llama31-70b_starcraft2_scene5_agent_vs_computer_randombuild_asyFalse.yaml",
# "eval_llama31-70b_starcraft2_scene6_agent_vs_computer_randombuild_asyTrue": "eval_llama31-70b_starcraft2_scene6_agent_vs_computer_randombuild_asyTrue.yaml",
# "eval_llama31-8b_starcraft2_scene1_agent_vs_computer_macro_asyFalse": "eval_llama31-8b_starcraft2_scene1_agent_vs_computer_macro_asyFalse.yaml",
# "eval_llama31-8b_starcraft2_scene2_agent_vs_computer_macro_asyTrue": "eval_llama31-8b_starcraft2_scene2_agent_vs_computer_macro_asyTrue.yaml",
# "eval_llama31-8b_starcraft2_scene3_agent_vs_computer_rush_asyFalse": "eval_llama31-8b_starcraft2_scene3_agent_vs_computer_rush_asyFalse.yaml",
# "eval_llama31-8b_starcraft2_scene4_agent_vs_computer_rush_asyTrue": "eval_llama31-8b_starcraft2_scene4_agent_vs_computer_rush_asyTrue.yaml",
# "eval_llama31-8b_starcraft2_scene5_agent_vs_computer_randombuild_asyFalse": "eval_llama31-8b_starcraft2_scene5_agent_vs_computer_randombuild_asyFalse.yaml",
# "eval_llama31-8b_starcraft2_scene6_agent_vs_computer_randombuild_asyTrue": "eval_llama31-8b_starcraft2_scene6_agent_vs_computer_randombuild_asyTrue.yaml",

##}